version: "3.9"
services:
  bukkit:
    image: ghcr.io/redstonewizard08/eaglercraft-docker/bukkit:main
    tty: true
    stdin_open: true
    ports:
      - "25569:25569"
    volumes:
      - ./data/bukkit:/bukkit
  bungee:
    image: ghcr.io/redstonewizard08/eaglercraft-docker/bungee:main
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      - ./data/bungee:/bungee
  nginx:
    image: ghcr.io/redstonewizard08/eaglercraft-docker/nginx:main
    tty: true
    stdin_open: true
    ports:
      - "3090:80"
